services:
  - type: web
    name: steganosafe
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install pandas --no-deps
    startCommand: gunicorn wsgi:app --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
