services:
  - type: web
    name: steganography-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://localhost:6379/0
