services:
  - type: web
    name: steganography-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn --worker-class eventlet -w 1 "wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PYTHONPATH
        value: .
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data/app.db
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
