openapi: 3.0.0
info:
  title: Steganography App API
  version: "1.0"
paths:
  /api/encrypt:
    post:
      summary: Encrypt an image with a hidden message.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                password:
                  type: string
                message:
                  type: string
      responses:
        "200":
          description: Encryption started.
  /api/login:
    post:
      summary: Log in a user.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful.
