"""Reinitializing migrations

Revision ID: acc8485d5954
Revises: 
Create Date: 2025-02-09 17:57:36.592688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc8485d5954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_stego_image')
    with op.batch_alter_table('stego_image', schema=None) as batch_op:
        batch_op.drop_column('salt')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('stego_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=255), nullable=True))

    op.create_table('_alembic_tmp_stego_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_encrypted', sa.BOOLEAN(), nullable=True),
    sa.Column('encryption_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('image_data', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
